/*
 *  Copyright (c) 2024 Victor M. Barrientos <firmw.guy@gmail.com>
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 *
 */

#ifndef CDP_PROCESS_H
#define CDP_PROCESS_H


/*
    Cascade Data Processing System - Layer 2
    ------------------------------------------

    ### System Overview:
    CascadeDP Layer 1 implemented a record system, intended to be used 
    as the basis of a RAM file system (similar to Plan 9). This Layer 2 
    is designed to handle data sharing and device management across a 
    distributed network of procesess. Each process can advertise its 
    capabilities and data, allowing for efficient resource sharing and 
    management within the network.

    ### Directory Structure:

    #### 1. **/system/**
    The `/system/` directory stores internal information needed by the 
    (distributed) record system. This is local to each node.
    - **Example Structure**:
      ```
      /system/
          /name/
              /name001
              /name002
              /type001
              /type002
          /type/
              /type001/
                  /nameID
                  /size
                  /description
      ```

    #### 2. **/instance/**
    The `/instance/` directory is used for storing (per process) 
    private records generated or used by the local node. This includes 
    registers and links as local resources that might be only accessed 
    inside each process instance.
    - **Example Structure**:
      ```
      /instance/
          /process001/
              /555/
                  /input/arg
                  /output/result -> /instance/process002/557/input/arg
              /556/
                  /input/arg
                  /output/result -> /instance/process002/558/input/arg
          /process002/
      ```

    #### 3. **/user/**
    This directory serves as the personal space for user-specific 
    configurations and data. Each user or administrative entity 
    interacting with the nodes might have a separate subdirectory here.
    This directory may be replicated to other nodes.
    - **Example Structure**:
      ```
      /user/
          /user1/
          /user2/
      ```

    #### 4. **~/private/**
    This sub-directory (inside a user's directory) stores peristent 
    records generated by processes and meant to be accessed only by the 
    (owner) user inside the current node. This directory is never 
    replicated.
    - **Example Structure**:
      ```
      /user/
          /user1/
              /private/
                  /process01/
                      /saved-data/
          /user2/
      ```

    #### 5. **/public/**
    The `/public/` directory is used for storing public records 
    generated or used by the processes in the network. This records are 
    advertised along this node when it connects to the network and may 
    be accessed (and/or cached/replicated) by other nodes.
    - **Example Structure**:
      ```
      /public/
          /process001/
              /instance/
                  /555/
                      /measurements/
                          /car01
              /shared/
                  /count
                  /events/
      ```

    #### 6. **/data/**
    The `/data/` directory is a virtual space used for accessing public 
    records generated or used by the processes in connected nodes. 
    This includes registers and links as shared resources that might be 
    accessed within the network.
    - **Example Structure**:
      ```
      /data/
          /process001/
              /measurements/
                  /car01 -> /network/node001/public/process001/instance/555/measurements/car01
                  /car02 -> /network/node002/public/process001/instance/333/measurements/car02
              /shared/   -> /network/node001/public/process001/shared/
      ```

    #### 7. **/process/**
    The `/process/` directory contains service description and process 
    specific resources (such as executables) necessary for the 
    registration, adverstising and loading of various processes in the
    nodes. This directory is replicated as needded in the whole network.
    - **Example Structure**:
      ```
      /process/
          /process001/
              /node -> /network/node001/
              /description
              /bin/
              /input/
              /output/
          /process002/
      ```

    #### 8. **/network/**
    This directory is central to managing network-specific 
    configurations and information about the reachability of each 
    (foreign) connected node with respect to the local one.
    - **Example Structure**:
      ```
      /network/
          /node001/
              /protocol
                  /address
                  /config/
                  /status
              /public/
          /node002/
      ```

    ### Additional Considerations:

    - **/config/**: Maintains system-wide configuration files that affect 
    all nodes and processes.
    - **/log/**: For comprehensive logging across the system, which 
    could include logs from each node, process, and application.
    - **/temp/**: Temporarily private records needed during execution,
    ensuring that transient data does not consume permanent storage space.
    - **/lib/**: Contains shared executables, libraries and drivers 
    needed by applications in `/process/`.

*/


#include "cdp_record.h"


// Initial CascadeDP system type and name IDs:
enum _CDP_ID {
    CDP_ID_NONE,

    // Book/Dictionary types
    CDP_ID_ROOT,      // For bootstrapping reasons this must be 0x01.
    CDP_ID_SYSTEM,
    CDP_ID_NAME,
    CDP_ID_TYPE,
    CDP_ID_INSTANCE,
    CDP_ID_USER,
    CDP_ID_PRIVATE,
    CDP_ID_PUBLIC,
    CDP_ID_DATA,
    CDP_ID_PROCESS,
    CDP_ID_NETWORK,
    
    // Register types
    CDP_ID_BOOLEAN,
    CDP_ID_UINT8,
    CDP_ID_UINT16,
    CDP_ID_UINT32,
    CDP_ID_UINT64,
    CDP_ID_SIGN16,
    CDP_ID_SIGN32,
    CDP_ID_SIGN64,
    CDP_ID_FLOAT32,
    CDP_ID_FLOAT64,
    CDP_ID_UTF8,
};


static inline cdpRecord* cdp_record_add_unsigned(cdpRecord* parent, cdpNameID name, unsigned value) {
    return cdp_record_add_register(parent, name, CDP_ID_UINT32, false, &value, sizeof(value));
}


typedef bool (*cdpCreate)(cdpRecord* instance, void** context);
typedef bool (*cdpInstance)(cdpRecord* instance, void* context);


cdpRecord* cdp_process_load(const char* name,
                            cdpCreate   create,
                            cdpInstance tic,
                            cdpInstance save,
                            cdpInstance restore,
                            cdpInstance destroy);


cdpNameID cdp_system_enter_name(const char* name, size_t length, bool staticStr);
cdpRecord* cdp_system_name(cdpNameID);
#define cdp_system_enter_name_string(str)   cdp_system_enter_name(str, strlen(str), true)


unsigned cdp_system_enter_type(cdpNameID nameID, size_t baseSize);
cdpRecord* cdp_system_type(unsigned typeID);

void cdp_system_initiate(void);
bool cdp_system_tic(void);
void cdp_system_shutdown(void);

#endif
