/*
 *  Copyright (c) 2024 Victor M. Barrientos (https://github.com/FirmwGuy/CacadeDP)
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  this software and associated documentation files (the "Software"), to deal in
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 *  of the Software, and to permit persons to whom the Software is furnished to do
 *  so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 *
 */

#ifndef CDP_SYSTEM_H
#define CDP_SYSTEM_H


/*
    Cascade Data Objecting System - Layer 2
    ------------------------------------------

    ### System Overview:
    CascadeDP Layer 1 implemented a record solution, intended to be used
    as the basis of a RAM file system (similar to Plan 9). This Layer 2
    is designed to handle a distributed system, that is, data sharing
    and service management across a network of devices.

    ### Agent:
    An agent is a smart record that can receive, handle and send
    tasks to other agents, processing events and information in
    behalf of the contained data (and may even propagate record
    instances all across the network). In a way, agents are executable
    functions that "travel" along the data they are bound to.

    The agent system uses a factory pattern combined with dynamic type
    specification and validation. This approach enables structured
    creation of record and instances, ensuring adherence to defined
    types while supporting graph-like relationships with multiple
    parents.
    - **Encapsulation**: Centralizes branched record creation logic.
    - **Consistency**: Enforces structure and metadata for each record type.
    - **Flexibility**: Facilitates adding new agents and dynamic creation.
    - **Separation of Concerns**: Decouples creation from business logic.
    - **Context-Aware Initialization**: Adapts structures based on
    parent relationships and specific requirements.

    ### Action:
    Agents perform the action contained in the tasks they receive.
    Actions differ depending of the context they are called (or
    signaled). The context is specified by the role agents had in
    assembled systems.

    ### Cascade:
    A Cascade is a system of agents acting (signaling) over other
    agent's records. In the cascade, connections are made by linking
    some agent's record to another agent's record, in such a way that
    one single action will produce a sequence of actions (domino
    effect style).

    ### Directory Structure:
    The base agent system is shaped by an universal hierarchycal
    data structure.

    (Note: In the following CascadeDP structures, record entries have an
    ID represented with text or number, and/or record value following
    the colom. Links are represented by the arrow "->".)

    #### 1. ** /system/ **
    The `/system/` dictionary stores internal information needed by the
    local record system, for example tags, names, etc.
    - **Example Structure**:
      ```
      /system/
          tag/
              1: "list"
              2: "integer"
          name/
              1: "data"
              2: "public"
          selector/
              10: "urgent"
              11: "slow"
          inhibitor/
              1: "heated"
              2: "loaded"
      ```

    #### 4. ** /user/ **
    This record serves as the personal space for user-specific
    configurations and data. Each user or administrative entity
    interacting with the nodes might have a separate entry here.
    This record may be replicated to other nodes.
    - **Example Structure**:
      ```
      /user/
          user1/
          user2/
      ```

    #### 5. ** ~/private/ **
    This record (inside a user's record) stores persistent records generated
    by agents and meant to be accessed only by the (owner) network
    user. This record is never replicated.
    - **Example Structure**:
      ```
      /user/
          user1/
              private/
                  system/
                      agent01/
                          555/
                             states/
                          556/
                             states/
                          saved-data/
      ```

    #### 6. ** /public/ **
    The `/public/` record is used for storing public records generated by
    the agents in the local node. These records are advertised along
    this node when it connects to the network and may be accessed
    (and/or cached/replicated) by other nodes.
    - **Example Structure**:
      ```
      /public/
          agent001/
              measurements/
                  car01/
              shared/
                  count:123
                  events/
      ```

    #### 7. ** /data/ **
    The `/data/` record is a virtual space used for mapping distributed
    public records into a communal coherent structure. This includes
    registers and links as shared resources that might be accessed
    within the network. This is replicated as needed.
    - **Example Structure**:
      ```
      /data/
          apps/
              agent001/
                  measurements/
                      car01 -> /network/node001/public/agent001/measurements/car01
                      car02 -> /network/node002/public/agent001/measurements/car02
                  shared/   -> /network/node001/public/agent001/shared/
      ```

    #### 8. ** /data/service/ **
    The `service/` record inside `/data/` contains the agent instance
    creation service (AICS) locations for available agents.
    - **Example Structure**:
      ```
      /data/
          service/
              agent001/
                  node -> /network/node001/system/agent001
                  node -> /network/node002/system/agent001

      ```

    #### 9. ** /network/ **
    This record is central to managing network-specific configurations
    and information about the reachability of each (foreign) connected
    node with respect to the local node.
    - **Example Structure**:
      ```
      /network/
          node001/
              protocol/
                  address
                  config/
                  status
      ```

    ### Additional Considerations:
    - ** /data/config/ **: Maintains system-wide configuration files that affect
    all nodes and agents.
    - ** /log/ and /data/log/ **: For comprehensive logging across the system,
    which could include logs from each node, agent, and application.
    - ** /temp/ **: Temporary private records needed during execution,
    ensuring that transient data does not consume permanent storage space.

*/


#include "cdp_record.h"


// Core directories
#define CDP_WORD_DATA       CDP_ID(0x0010340800000000)      /* "data"_______ */
#define CDP_WORD_NETWORK    CDP_ID(0x0038B4BBE4B00000)      /* "network"____ */
#define CDP_WORD_PUBLIC     CDP_ID(0x0042A26246000000)      /* "public"_____ */
#define CDP_WORD_PRIVATE    CDP_ID(0x004249B068500000)      /* "private"____ */
#define CDP_WORD_SYSTEM     CDP_ID(0x004F33A15A000000)      /* "system"_____ */
#define CDP_WORD_TEMP       CDP_ID(0x0050AD8000000000)      /* "temp"_______ */
#define CDP_WORD_USER       CDP_ID(0x0056659000000000)      /* "user"_______ */


// Core sub-dirs
#define CDP_WORD_AGENT      CDP_ID(0x0004E57500000000)      /* "agent"______ */
#define CDP_WORD_CASCADE    CDP_ID(0x000C331848500000)      /* "cascade"____ */
#define CDP_WORD_DOMAIN     CDP_ID(0x0011ED0A5C000000)      /* "domain"_____ */
#define CDP_WORD_LIBRARY    CDP_ID(0x0031229065900000)      /* "library"____ */

#define CDP_WORD_STEP       CDP_ID(0x004E858000000000)      /* "step"_______ */


// Basic fields
//#define CDP_WORD_PENDING    CDP_ID(0x0000000000000000)      /* "pending"     */
//#define CDP_WORD_WORKING    CDP_ID(0x0000000000000000)      /* "working"     */
//#define CDP_WORD_COMPLETED  CDP_ID(0x0000000000000000)      /* "completed"   */
//#define CDP_WORD_FAILED     CDP_ID(0x0000000000000000)      /* "failed"      */

// Events
//#define CDP_WORD_DEBUG      CDP_ID(0x0000000000000000)      /* "debug"       */
//#define CDP_WORD_WARNING    CDP_ID(0x0000000000000000)      /* "warning"     */
//#define CDP_WORD_ERROR      CDP_ID(0x0000000000000000)      /* "error"       */
//#define CDP_WORD_FATAL      CDP_ID(0x0000000000000000)      /* "fatal"       */


void      cdp_system_register_agent(cdpID domain, cdpID tag, cdpAgent agent);
cdpAgent  cdp_system_agent(cdpID domain, cdpID tag);

bool      cdp_system_startup(void);
bool      cdp_system_step(void);
void      cdp_system_shutdown(void);


static inline cdpRecord* cdp_void(void)  {extern cdpRecord* CDP_VOID; assert(CDP_VOID);  return CDP_VOID;}

static inline cdpRecord* cdp_agent_step(void)  {extern cdpRecord* CDP_STEP; assert(CDP_STEP);  return CDP_STEP;}


static inline cdpRecord* cdp_cascade_get_inlet(cdpRecord* client, cdpRecord* self, cdpID inlet) {
    assert(!cdp_record_is_void(client) && !cdp_record_is_empty(self) && cdp_id_text_valid(inlet));
    cdpRecord* found;

    if (cdp_record_has_data(self)) {
        for (cdpAgentList* list = self->data->agent;  list;  list = list->next) {
            found = list->agent(client, self, CDP_ACTION_GET_INLET, NULL, CDP_V(inlet));
            if (found)
                return found;
        }
    }

    if (cdp_record_has_store(self)) {
        for (cdpAgentList* list = self->store->agent;  list;  list = list->next) {
            found = list->agent(client, self, CDP_ACTION_GET_INLET,  NULL, CDP_V(inlet));
            if (found)
                return found;
        }
    }

    return NULL;
}


static inline cdpRecord* cdp_cascade_connect(cdpRecord* client, cdpRecord* self, cdpID output, cdpRecord* inlet) {
    assert(!cdp_record_is_void(client) && !cdp_record_is_unset(self) && cdp_id_text_valid(output) && !cdp_record_is_floating(inlet));
    cdpRecord* found;

    if (cdp_record_has_data(self)) {
        for (cdpAgentList* list = self->data->agent;  list;  list = list->next) {
            found = list->agent(client, self, CDP_ACTION_CONNECT, inlet, CDP_V(output));
            if (found)
                return found;
        }
    }

    if (cdp_record_has_store(self)) {
        for (cdpAgentList* list = self->store->agent;  list;  list = list->next) {
            found = list->agent(client, self, CDP_ACTION_CONNECT, inlet, CDP_V(output));
            if (found)
                return found;
        }
    }

    return NULL;
}


static inline cdpRecord* cdp_cascade_unplug(cdpRecord* client, cdpRecord* self, cdpRecord* output) {
    assert(!cdp_record_is_void(client) && !cdp_record_is_empty(self) && !cdp_record_is_floating(output));
    cdpRecord* found;

    if (cdp_record_has_data(self)) {
        for (cdpAgentList* list = self->data->agent;  list;  list = list->next) {
            found = list->agent(client, self, CDP_ACTION_UNPLUG, output, CDP_V(0));
            if (found)
                return found;
        }
    }

    if (cdp_record_has_store(self)) {
        for (cdpAgentList* list = self->store->agent;  list;  list = list->next) {
            found = list->agent(client, self, CDP_ACTION_UNPLUG, output, CDP_V(0));
            if (found)
                return found;
        }
    }

    return NULL;
}


static inline cdpData* cdp_cascade_data_new(cdpRecord* client, cdpRecord* self, cdpID domain, cdpID tag, cdpRecord* params, cdpValue value) {
    self = cdp_link_pull(self);
    assert(!cdp_record_is_void(client) && !cdp_record_has_data(self));

    cdpAgent agent = cdp_system_agent(domain, tag);

    if (!agent || !agent(client, self, CDP_ACTION_DATA_NEW, params, value))
        return NULL;

    cdp_data_add_agent(self->data, domain, tag, agent);

    return self->data;
}


static inline cdpData* cdp_cascade_data_update(cdpRecord* client, cdpRecord* self, size_t size, size_t capacity, cdpValue data) {
    self = cdp_link_pull(self);
    assert(!cdp_record_is_void(client) && cdp_record_has_data(self));

    cdp_record_update(self, size, capacity, data, false);

    for (cdpAgentList* list = self->data->agent;  list;  list = list->next) {
        if (!list->agent(client, self, CDP_ACTION_DATA_UPDATE, NULL, data))
            return NULL;
    }

    return self->data;
}


static inline bool cdp_cascade_data_dalete(cdpRecord* client, cdpRecord* self) {
    self = cdp_link_pull(self);
    assert(!cdp_record_is_void(client) && !cdp_record_is_void(self));

    cdpAgentList* list;

    if (cdp_record_has_data(self)) {
        list = self->data->agent;
        self->data->agent = NULL;

        cdp_record_delete_data(self);
    } else {
        list = NULL;
    }

    bool ok = true;

    while (list) {
        cdpAgentList* next = list->next;
        if (ok && !list->agent(client, self, CDP_ACTION_DATA_DELETE, NULL, CDP_V(0)))
            ok = false;

        cdp_agent_list_del(list);
        list = next;
    }

    return ok;
}


static inline cdpStore* cdp_cascade_store_new(cdpRecord* client, cdpRecord* self, cdpID domain, cdpID tag, cdpRecord* params, cdpValue value) {
    self = cdp_link_pull(self);
    assert(!cdp_record_is_void(client) && !cdp_record_has_store(self));

    cdpAgent agent = cdp_system_agent(domain, tag);

    if (!agent || !agent(client, self, CDP_ACTION_STORE_NEW, params, value))
        return NULL;

    cdp_store_add_agent(self->store, domain, tag, agent);

    return self->store;
}


static inline cdpRecord* cdp_cascade_store_add_item(cdpRecord* client, cdpRecord* self, cdpRecord* child, cdpValue context) {
    self = cdp_link_pull(self);
    child   = cdp_link_pull(child);
    assert(!cdp_record_is_void(client) && cdp_record_has_store(self) && !cdp_record_is_void(child));

    cdpRecord* r = cdp_record_add(self, context, child);

    for (cdpAgentList* list = self->store->agent;  list;  list = list->next) {
        if (!list->agent(client, self, CDP_ACTION_STORE_ADD_ITEM, r, CDP_V(0)))
            return NULL;
    }

    return r;
}


static inline bool cdp_cascade_store_remove_item(cdpRecord* client, cdpRecord* self, cdpRecord* child) {
    assert(!cdp_record_is_void(client) && !cdp_record_is_void(child));

    if (!self)
        self = cdp_record_parent(child);
    assert(cdp_record_has_store(self));

    for (cdpAgentList* list = self->store->agent;  list;  list = list->next) {
        if (!list->agent(client, self, CDP_ACTION_STORE_REMOVE_ITEM, child, CDP_V(0)))
            return false;
    }

    cdp_record_remove(child, NULL);

    return true;
}


static inline bool cdp_cascade_store_delete(cdpRecord* client, cdpRecord* self) {
    self = cdp_link_pull(self);
    assert(!cdp_record_is_void(client) && !cdp_record_is_void(self));

    cdpAgentList* list;

    if (cdp_record_has_store(self)) {
        list = self->store->agent;
        self->store->agent = NULL;

        cdp_record_delete_store(self);
    } else {
        list = NULL;
    }

    bool ok = true;

    while (list) {
        cdpAgentList* next = list->next;
        if (ok && !list->agent(client, self, CDP_ACTION_STORE_DELETE, NULL, CDP_V(0)))
            ok = false;

        cdp_agent_list_del(list);
        list = next;
    }

    return ok;
}


static inline cdpRecord* cdp_cascade_record_new(  cdpRecord* client, cdpRecord* self,
                                                  cdpID name, cdpID domain, cdpID tag,
                                                  cdpRecord* dataParam, cdpValue dataValue,
                                                  cdpRecord* storeParam, cdpValue storeValue  ) {
    assert(!cdp_record_is_void(client) && cdp_record_is_void(self));

    cdp_record_initialize(self, CDP_TYPE_NORMAL, name, NULL, NULL);

    cdpData*  data  = cdp_cascade_data_new (client, self, domain, tag, dataParam,  dataValue);
    cdpStore* store = cdp_cascade_store_new(client, self, domain, tag, storeParam, storeValue);
    if (!data && !store) {
        cdp_record_finalize(self);
        return NULL;
    }

    return self;
}


#endif
